### ISSUE TITLE
[Feature Request] Update snap to latest Gnome stack like gnome-42 and update snap core version to core22

### ISSUE THREAD

**Issue by CapeCrusader321** [aandrew-me/ytDownloader#113]
**Description**
The Snap version  uses outdated version of Snap base and Core, please use new core and base snap..

**Comment by aandrew-me** [comment]
Hello,
Thanks for mentioning this. I haven't even noticed that `electron-builder` was using such an old `base`. Moreover they didn't even provide a way to change the `base` . However I still found a way to change the `base`.
[
Snapcraft recommends core20](https://snapcraft.io/docs/base-snaps#heading--supported). However I will use core22 and if there are any problems, I will switch to core20.

Have a good day

**Comment by aandrew-me** [comment]
Ok I was able to build with core22. I have published the update to Snapcraft.

Now its using core22
```
>> snap info --verbose ytdownloader
name:      ytdownloader
summary:   Download videos and audios from Youtube and hundreds of other sites.
publisher: Andrew (aandreww)
store-url: https://snapcraft.io/ytdownloader
links:
  website:
    - https://github.com/aandrew-me/ytdownloader
license: AGPL-3.0
description: |
  Ytdownloader is a Free and Open source GUI app for downloading videos and audios from Youtube and
  hundreds of other sites including but not limited to Facebook, Instagram, Twitter, Tiktok, Twitch
  and so on..
  
  Source Code - https://github.com/aandrew-me/ytdownloader
notes:         
  private:     false
  confinement: strict
base:    core22
snap-id: gUWL3Wjxk7CmprKFts2KPsznR1ODvt0N
channels:
  latest/stable:    3.12.0 2023-02-26 (38) 117MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      3.12.0 2023-02-26 (38) 117MB -
```

**Comment by CapeCrusader321** [comment]
Thanks for Checking Out, I also request you to update the runtime, it currently use gnome gnome-3-28-1804, which is pretty ancient, try to use gnome-42-2204 or even gnome-3-38-2004.

**Comment by aandrew-me** [comment]
I am trying to find a way

**Comment by CapeCrusader321** [comment]
Ok, i think you may be having a extension area in Your Snap YAML, please check or search for it...

**Comment by aandrew-me** [comment]
For some reason, whenever I am adding gnome-42, app is not launching and I am getting errors.

You can check if its the same for you
`sudo snap install ytdownloader --edge`

**Comment by CapeCrusader321** [comment]
ok will try

**Comment by CapeCrusader321** [comment]
> For some reason, whenever I am adding gnome-42, app is not launching and I am getting errors.
> 
> You can check if its the same for you `sudo snap install ytdownloader --edge`

It works fine, downloaded from edge channel

**Comment by aandrew-me** [comment]
Ok great, is it using gnome-42 or the legacy gnome-3-28-1804?

**Comment by aandrew-me** [comment]
Also I pushed an update to edge (46th revision). Check if that works

**Comment by CapeCrusader321** [comment]
No its using legacy gnome 28, will try the new revision

**Comment by CapeCrusader321** [comment]
> Also I pushed an update to edge (46th revision). Check if that works

The revision wont work without gnome-3-28-1804 the legacy stack

**Comment by aandrew-me** [comment]
Ok Thanks for letting me know, let me make some changes and I will push another update

**Comment by CapeCrusader321** [comment]
Can you please share your snapcraft yaml ??

**Comment by CapeCrusader321** [comment]
The new updates have made the app not to open, downloaded the recent version..

**Comment by aandrew-me** [comment]
> The new updates have made the app not to open, downloaded the recent version..

Yeah that happened as I removed gnome-3-28-1804

**Comment by aandrew-me** [comment]
The fact is, I use electron builder to build the app. So they handle the snapcraft.yaml file. What I have to do is instead specify the necessary options in package.json file. And they are still using core-18 to package with gnome-3-28-1804. Only in Alpha version of the tool they added support to change core, but that still uses the legacy gnome-3-28-1804. But there is a snapcraft.yaml file that can be modified, though its not the official way. So in package.json file I add
```
"snap": {
			"grade": "stable",
			"base": "core22",
			"plugs": [
				{
					"gnome-42-2204": {
						"interface": "content",
						"target": "$SNAP/gnome-platform",
						"default-provider": "gnome-42-2204"
					}
				}
			]
		}
```
And here is the snapcraft.yaml file
```
base: core18
grade: stable
confinement: strict
parts:
  launch-scripts:
    plugin: dump
    source: scripts
  gnome-platform-empty-dirs:
    plugin: nil
    override-build: >
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/themes"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/icons"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/sounds"
      mkdir $SNAPCRAFT_PART_INSTALL/gnome-platform

  app-files:
    plugin: dump
    source: app
    organize:
      '*': app/
    stage:
      - -app/chrome-sandbox
      - -LICENSES.chromium.html
  app:
    plugin: "nil"
      # cd ~ && rm -rf ~/squashfs-root && unsquashfs /media/psf/ramdisk/electron-builder-test/dist/__snap-x64/se-wo-template_1.1.0_amd64.snap
      # comm -12 <(ls ~/squashfs-root/usr/lib/x86_64-linux-gnu/) <(ls /snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/) > /media/psf/Home/f.txt
      # run snap-exclude-list.js
    stage:
      - '-usr/lib/python*'
      - '-usr/bin/python*'
      - '-var/lib/ucf'
      - '-usr/include'
      - '-usr/lib/X11'
      - '-usr/share'
      - '-usr/sbin'
      - '-usr/bin'
      - "-usr/lib/*/libicudata.*"
      - "-usr/lib/*/libicui18n.*"
      - "-usr/lib/*/libgtk-*"
      - "-usr/lib/*/libgdk-*"
      - "-usr/lib/*/glib-*"
      - "-usr/lib/*/gtk-*"
      - "-usr/lib/*/gdk-*"
      - "-usr/lib/*/krb5"
      - "-usr/lib/systemd"
      - "-usr/lib/glib-networking"
      - "-usr/lib/dconf"
      - "-usr/lib/*/avahi"
      - "-usr/lib/*/gio"
      - "-usr/lib/*/libatk*"
      - "-usr/lib/*/libatspi*"
      - "-usr/lib/*/libavahi*"
      - "-usr/lib/*/libcairo*"
      - "-usr/lib/*/libcolordprivate*"
      - "-usr/lib/*/libcolord*"
      - "-usr/lib/*/libcroco*"
      - "-usr/lib/*/libcups*"
      - "-usr/lib/*/libdatrie*"
      - "-usr/lib/*/libdconf*"
      - "-usr/lib/*/libepoxy*"
      - "-usr/lib/*/libexpatw*"
      - "-usr/lib/*/libffi*"
      - "-usr/lib/*/libfontconfig*"
      - "-usr/lib/*/libfreetype*"
      - "-usr/lib/*/libgdk_pixbuf*"
      - "-usr/lib/*/libgdk_pixbuf_xlib*"
      - "-usr/lib/*/libgio*"
      - "-usr/lib/*/libglib*"
      - "-usr/lib/*/libgmodule*"
      - "-usr/lib/*/libgmp*"
      - "-usr/lib/*/libgnutls*"
      - "-usr/lib/*/libgobject*"
      - "-usr/lib/*/libgraphite2*"
      - "-usr/lib/*/libgssapi_krb5*"
      - "-usr/lib/*/libgthread*"
      - "-usr/lib/*/libharfbuzz*"
      - "-usr/lib/*/libhogweed*"
      - "-usr/lib/*/libicuio*"
      - "-usr/lib/*/libicutest*"
      - "-usr/lib/*/libicutu*"
      - "-usr/lib/*/libicuuc*"
      - "-usr/lib/*/libidn2*"
      - "-usr/lib/*/libjbig*"
      - "-usr/lib/*/libjpeg*"
      - "-usr/lib/*/libjson*"
      - "-usr/lib/*/libk5crypto*"
      - "-usr/lib/*/libkrb5*"
      - "-usr/lib/*/libkrb5support*"
      - "-usr/lib/*/liblcms2*"
      - "-usr/lib/*/libnettle*"
      - "-usr/lib/*/libp11*"
      - "-usr/lib/*/libpango*"
      - "-usr/lib/*/libpangocairo*"
      - "-usr/lib/*/libpangoft2*"
      - "-usr/lib/*/libpixman*"
      - "-usr/lib/*/libpng16*"
      - "-usr/lib/*/libproxy*"
      - "-usr/lib/*/librest*"
      - "-usr/lib/*/librsvg*"
      - "-usr/lib/*/libsecret*"
      - "-usr/lib/*/libsoup*"
      - "-usr/lib/*/libsqlite3*"
      - "-usr/lib/*/libtasn1*"
      - "-usr/lib/*/libthai*"
      - "-usr/lib/*/libtiff*"
      - "-usr/lib/*/libunistring*"
      - "-usr/lib/*/libwayland*"
      - "-usr/lib/*/libX11*"
      - "-usr/lib/*/libXau*"
      - "-usr/lib/*/libxcb.so*"
      - "-usr/lib/*/libxcb-dri2*"
      - "-usr/lib/*/libxcb-dri3*"
      - "-usr/lib/*/libxcb-glx*"
      - "-usr/lib/*/libxcb-present*"
      - "-usr/lib/*/libxcb-render*"
      - "-usr/lib/*/libxcb-shm*"
      - "-usr/lib/*/libxcb-sync*"
      - "-usr/lib/*/libxcb-xfixes*"
      - "-usr/lib/*/libXcomposite*"
      - "-usr/lib/*/libXcursor*"
      - "-usr/lib/*/libXdamage*"
      - "-usr/lib/*/libXdmcp*"
      - "-usr/lib/*/libXext*"
      - "-usr/lib/*/libXfixes*"
      - "-usr/lib/*/libXinerama*"
      - "-usr/lib/*/libXi*"
      - "-usr/lib/*/libxkbcommon*"
      - "-usr/lib/*/libxml2*"
      - "-usr/lib/*/libXrandr*"
      - "-usr/lib/*/libXrender*"
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
```
core18 is overridden by core22 from package.json file
In the recent edge update I had removed the gnome-3-28-1804 part and looks like it broke the app.

**Comment by CapeCrusader321** [comment]
Yes thats the problem remove all the gnome parts part, the latest gnome extension can be added with a single command, thats just add extension block to the app part and enter value --> [gnome], thats it remove all other gnome part, the new one automatically adds all those option so no need to specify them remove the complete last part of gnome

**Comment by CapeCrusader321** [comment]
Do it like this : 
app:
    extensions: [gnome]

DONE !!

**Comment by CapeCrusader321** [comment]
try to edit the snap yaml manually

**Comment by aandrew-me** [comment]
You mean removing the `plugs`?
```
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
```

**Comment by CapeCrusader321** [comment]
yes

**Comment by CapeCrusader321** [comment]
remove them completely, the new one adds them automatically

**Comment by CapeCrusader321** [comment]
do re share the modified yaml

**Comment by aandrew-me** [comment]
```
base: core18
grade: stable
confinement: strict
parts:
  launch-scripts:
    plugin: dump
    source: scripts
  gnome-platform-empty-dirs:
    plugin: nil
    override-build: >
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/themes"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/icons"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/data-dir/sounds"
      mkdir $SNAPCRAFT_PART_INSTALL/gnome-platform

  app-files:
    plugin: dump
    source: app
    organize:
      '*': app/
    stage:
      - -app/chrome-sandbox
      - -LICENSES.chromium.html
  app:
    extensions: [gnome]
    plugin: "nil"
      # cd ~ && rm -rf ~/squashfs-root && unsquashfs /media/psf/ramdisk/electron-builder-test/dist/__snap-x64/se-wo-template_1.1.0_amd64.snap
      # comm -12 <(ls ~/squashfs-root/usr/lib/x86_64-linux-gnu/) <(ls /snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/) > /media/psf/Home/f.txt
      # run snap-exclude-list.js
    stage:
      - '-usr/lib/python*'
      - '-usr/bin/python*'
      - '-var/lib/ucf'
      - '-usr/include'
      - '-usr/lib/X11'
      - '-usr/share'
      - '-usr/sbin'
      - '-usr/bin'
      - "-usr/lib/*/libicudata.*"
      - "-usr/lib/*/libicui18n.*"
      - "-usr/lib/*/libgtk-*"
      - "-usr/lib/*/libgdk-*"
      - "-usr/lib/*/glib-*"
      - "-usr/lib/*/gtk-*"
      - "-usr/lib/*/gdk-*"
      - "-usr/lib/*/krb5"
      - "-usr/lib/systemd"
      - "-usr/lib/glib-networking"
      - "-usr/lib/dconf"
      - "-usr/lib/*/avahi"
      - "-usr/lib/*/gio"
      - "-usr/lib/*/libatk*"
      - "-usr/lib/*/libatspi*"
      - "-usr/lib/*/libavahi*"
      - "-usr/lib/*/libcairo*"
      - "-usr/lib/*/libcolordprivate*"
      - "-usr/lib/*/libcolord*"
      - "-usr/lib/*/libcroco*"
      - "-usr/lib/*/libcups*"
      - "-usr/lib/*/libdatrie*"
      - "-usr/lib/*/libdconf*"
      - "-usr/lib/*/libepoxy*"
      - "-usr/lib/*/libexpatw*"
      - "-usr/lib/*/libffi*"
      - "-usr/lib/*/libfontconfig*"
      - "-usr/lib/*/libfreetype*"
      - "-usr/lib/*/libgdk_pixbuf*"
      - "-usr/lib/*/libgdk_pixbuf_xlib*"
      - "-usr/lib/*/libgio*"
      - "-usr/lib/*/libglib*"
      - "-usr/lib/*/libgmodule*"
      - "-usr/lib/*/libgmp*"
      - "-usr/lib/*/libgnutls*"
      - "-usr/lib/*/libgobject*"
      - "-usr/lib/*/libgraphite2*"
      - "-usr/lib/*/libgssapi_krb5*"
      - "-usr/lib/*/libgthread*"
      - "-usr/lib/*/libharfbuzz*"
      - "-usr/lib/*/libhogweed*"
      - "-usr/lib/*/libicuio*"
      - "-usr/lib/*/libicutest*"
      - "-usr/lib/*/libicutu*"
      - "-usr/lib/*/libicuuc*"
      - "-usr/lib/*/libidn2*"
      - "-usr/lib/*/libjbig*"
      - "-usr/lib/*/libjpeg*"
      - "-usr/lib/*/libjson*"
      - "-usr/lib/*/libk5crypto*"
      - "-usr/lib/*/libkrb5*"
      - "-usr/lib/*/libkrb5support*"
      - "-usr/lib/*/liblcms2*"
      - "-usr/lib/*/libnettle*"
      - "-usr/lib/*/libp11*"
      - "-usr/lib/*/libpango*"
      - "-usr/lib/*/libpangocairo*"
      - "-usr/lib/*/libpangoft2*"
      - "-usr/lib/*/libpixman*"
      - "-usr/lib/*/libpng16*"
      - "-usr/lib/*/libproxy*"
      - "-usr/lib/*/librest*"
      - "-usr/lib/*/librsvg*"
      - "-usr/lib/*/libsecret*"
      - "-usr/lib/*/libsoup*"
      - "-usr/lib/*/libsqlite3*"
      - "-usr/lib/*/libtasn1*"
      - "-usr/lib/*/libthai*"
      - "-usr/lib/*/libtiff*"
      - "-usr/lib/*/libunistring*"
      - "-usr/lib/*/libwayland*"
      - "-usr/lib/*/libX11*"
      - "-usr/lib/*/libXau*"
      - "-usr/lib/*/libxcb.so*"
      - "-usr/lib/*/libxcb-dri2*"
      - "-usr/lib/*/libxcb-dri3*"
      - "-usr/lib/*/libxcb-glx*"
      - "-usr/lib/*/libxcb-present*"
      - "-usr/lib/*/libxcb-render*"
      - "-usr/lib/*/libxcb-shm*"
      - "-usr/lib/*/libxcb-sync*"
      - "-usr/lib/*/libxcb-xfixes*"
      - "-usr/lib/*/libXcomposite*"
      - "-usr/lib/*/libXcursor*"
      - "-usr/lib/*/libXdamage*"
      - "-usr/lib/*/libXdmcp*"
      - "-usr/lib/*/libXext*"
      - "-usr/lib/*/libXfixes*"
      - "-usr/lib/*/libXinerama*"
      - "-usr/lib/*/libXi*"
      - "-usr/lib/*/libxkbcommon*"
      - "-usr/lib/*/libxml2*"
      - "-usr/lib/*/libXrandr*"
      - "-usr/lib/*/libXrender*"
```
I tried building with the new yaml but still getting some error
